export const UPDATE_CART = 'UPDATE_CART';
export const FETCH_CART= 'FETCH_CART';
export const ADD_TO_CART= 'ADD_TO_CART';
export const REMOVE_FROM_CART= 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM= 'UPDATE_CART_ITEM';